import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import CommonLayout from "@/components/commonLayout";
import SmoothScroll from "@/components/SmoothScroll";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const figtree = localFont({
  variable: "--font-figtree",
  src: [
    { path: "../font/Figtree-Regular.ttf", weight: "400", style: "normal" },
    { path: "../font/Figtree-Bold.ttf", weight: "700", style: "normal" },
    { path: "../font/Figtree-Black.ttf", weight: "900", style: "normal" },
  ],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${figtree.variable} h-full antialiased`}
    >
        <body className="min-h-full bg-slate-50 font-figtree">
      <SmoothScroll>
          <CommonLayout>{children}</CommonLayout>
      </SmoothScroll>
        </body>
    </html>
  );
}
